# Generated by Django 5.0.7 on 2024-08-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Mymodel",
        ),
        migrations.AlterModelOptions(
            name="ad",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "Отзыв", "verbose_name_plural": "Отзывы"},
        ),
    ]
